### ISSUE TITLE
trying a test, does not work

### ISSUE THREAD

**Issue by mycode-bit** [paulsbond/modelcraft#8]
Hello,

I am new to x-ray crystal structure, and trying to do automation.
I used fast_2a8d.mtz, fast_2a8d.seq  as example for the test, the file was use for CPP4 tutorial (find over here: http://legacy.ccp4.ac.uk/tutorials/data/HICA.tgz).
when I run modelcraft --data fast_2a8d.mtz --content fast_2a8d.seq --model fast_1i6p.pdb, 
it does not work, showing error: Job-2-refmac5/hklout.mtz: no such file or directory.

Could you tell me what could be the problem?

Thanks
Tom

**Comment by mycode-bit** [comment]
addition question is that when I uninstall and install modelcraft, it showed different requirement, such as --hlkin is required, instead of --data. why? is there different version?

**Comment by paulsbond** [comment]
Hi Tom,

Thanks for linking the files. In this case, REFMAC gives an error because there are waters in the input model without a chain label (there is a clue to this at the bottom of job_2_refmac/stdout.txt). I will make a note to improve my error messages as saying that a specific file doesn't exist isn't very helpful.

If you remove the waters from the model then ModelCraft should run without an error. However, before using ModelCraft for model building, you need to use a molecular replacement program to place copies of the 1i6p model into the cell of 2a8d. The output model from molecular replacement (before refinement) should then be used as input to ModelCraft. More specific instructions for this case can be found at https://www.ccp4.ac.uk/?page_id=1072.

I think when you are re-installing you may be doing it with a different python interpreter. The --hklin argument is from a much older version. If you install with Python3.7+ you should get the latest 1.0.0 release.

Cheers,
Paul

**Comment by mycode-bit** [comment]
Thanks Paul, appreciate it. I will give a try.
